# Use an official OpenJDK image as a base
FROM openjdk:17-jdk-alpine

# Add a volume pointing to /tmp
VOLUME /tmp

# Set the working directory to /app
WORKDIR /app

# Copy the packaged jar file into the container
COPY target/your-app-name.jar app.jar

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java","-jar","/app/Pokedex-0.0.1-SNAPSHOT.jar"]